// Generated by Codex/OpenAI build.mjs; optional Worker adapter, not a deployment.
import { handleEphemerisRequest, handleDataRequest } from './api.mjs';
export function createWorker({ ephemeris, issData, ephemerisPackage, issTelemetry } = {}) {
  return { async fetch(request, env = {}) {
    const url = new URL(request.url);
    if (url.pathname === '/api/ephemeris') return handleEphemerisRequest(request, { ephemeris });
    if (['/api/iss-data','/api/ephemeris-package','/api/iss-telemetry'].includes(url.pathname)) return handleDataRequest(request,{issData,ephemerisPackage,issTelemetry});
    if (url.pathname.startsWith('/api/')) return new Response('Not found', { status: 404 });
    if (request.method !== 'GET' && request.method !== 'HEAD') return new Response(null, { status: 405, headers: { Allow: 'GET, HEAD' } });
    if (!env.ASSETS || typeof env.ASSETS.fetch !== 'function') return new Response('Static asset binding required', { status: 503 });
    const asset = await env.ASSETS.fetch(request);
    const headers = new Headers(asset.headers);
    headers.set('X-Content-Type-Options', 'nosniff');
    headers.set('Content-Security-Policy', "default-src 'self'; style-src 'self'; script-src 'self' blob:; worker-src 'self' blob:; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
    return new Response(request.method === 'HEAD' ? null : asset.body, { status: asset.status, statusText: asset.statusText, headers });
  } };
}
export default createWorker();
